#!/bin/zsh

#brew update
brew install tmux
brew install tldr
brew install tree
brew install the_silver_searcher
brew install stow
brew install rectangle
brew install z
brew install jq
brew install fd
brew install kubernetes-cli
brew install kubectx
brew install siege
brew install helm
brew install zsh-syntax-highlighting

ZSH="$HOME/dotfiles/oh-my-zsh" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
